### ISSUE TITLE
Cannot run in iOS 6 Simulator

### ISSUE THREAD

**Issue by objectmethod** [michaeljbishop/NGAParallaxMotion#4]
I assumed that this category would degrade more gracefully if running on iOS 6, but I'm unable to run at all. I'm getting the following error:

dyld: Symbol not found: _OBJC_CLASS_$_UIInterpolatingMotionEffect
  Referenced from: /Users/RichardGuy/Library/Application Support/iPhone Simulator/6.0/Applications/19E194FD-988A-4499-9EB1-A559989359C9/Nibblr.app/Nibblr
  Expected in: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 in /Users/RichardGuy/Library/Application Support/iPhone Simulator/6.0/Applications/19E194FD-988A-4499-9EB1-A559989359C9/Nibblr.app/Nibblr
(lldb)

**Comment by michaeljbishop** [comment]
My bad. I'll try to fix this ASAP.

**Comment by michaeljbishop** [comment]
I think I fixed it. Can you try this

https://github.com/michaeljbishop/NGAParallaxMotion/commit/a4b457ee6b158203994e03f530739cf27f0c5fd3

And close the issue if it fixes your problem?

**Comment by objectmethod** [comment]
No, it still crashes. Here's a screenshot: http://d.pr/i/BPex

It appears to be at compilation time vs runtime, so just the presence of it causes it to crash, like this: http://d.pr/i/uuuB

**Comment by michaeljbishop** [comment]
Hmmm... Here's my test: I open the Demo project in XCode5.

## Building

I can build the project against both the iOS7 SDK and the iOS6 SDK. With the iOS6 SDK, I get a warning that the feature will be disabled.

## Runtime

When I run the version built with the iOS6SDK, I get nothing on iOS6 or 7.
When I run the version built with the iOS7 SDK, I get the effect in the iOS7 Simulator and nothing in the iOS6 Simulator (but it doesn't crash).

Does that not work for you either?

**Comment by objectmethod** [comment]
Yeah, I see that now. I just downloaded your demo project, and it's running fine.  Let me try to figure out the differences in our projects then.

**Comment by michaeljbishop** [comment]
Thanks. I'm curious to see what you find. Are you using cocoapods?

**Comment by objectmethod** [comment]
EXACTLY what I just discovered!  Your timing couldn't have been better. When I removed your locally-referenced classes from your demo project and used cocoapods instead, it broke! :)

**Comment by michaeljbishop** [comment]
That makes sense. I haven't updated the cocoapods version to 1.0.1 (which would include this fix) because I wanted to make sure the fix worked before I bumped the version number.
Can you please manually use these source files in your other project and see if it works? I'd like to bump the cocoapods version number and put this out.

**Comment by objectmethod** [comment]
Yep. That worked!

**Comment by michaeljbishop** [comment]
Great! Thanks. I'll bump the version and update the CocoaPod and get back to you...

**Comment by michaeljbishop** [comment]
Watch this space...

https://github.com/CocoaPods/Specs/pull/4433

**Comment by michaeljbishop** [comment]
Ok, you are good to go. Thanks for the bug report. That was very helpful.

**Comment by objectmethod** [comment]
Even installing 1.0.1 via CocoaPods still produces that same error! :(

**Comment by michaeljbishop** [comment]
I think the problem is that UIKit needs to be weakly linked.

**Comment by michaeljbishop** [comment]
I'm guessing it crashes before your app has even run?

**Comment by objectmethod** [comment]
Yes, exactly.

**Comment by michaeljbishop** [comment]
I think I know what the problem is. Let me run some tests. If this is the problem, it makes sense that my project worked but that it doesn't in a podspec environment. I'm a little new to podspecs so I'll need a little time to test.

**Comment by michaeljbishop** [comment]
Can you try this?
Open up your podfile and put this at the top

```
# Uncomment this line to define a global platform for your project
platform :ios, "6.0"
```

The run `pod update` (I think. Whatever command regenerates the pod workspace)

**Comment by michaeljbishop** [comment]
The problem is that the final project that is compiling the pod code has a deployment target of 7.0. That means that the symbols for `UIInterpolatingMotionEffect` are being _hard_-linked. When the app starts the runtime can't find the symbol and the whole thing crashes. If the project had a deployment target of 6.0, the symbol would be _weak_-linked and would present no problem. I'm trying to figure out what setting in the podspec will make sure the deployment target is properly set.

**Comment by michaeljbishop** [comment]
Okay, now let's wait for _this_...

https://github.com/CocoaPods/Specs/pull/4437

**Comment by michaeljbishop** [comment]
Ok, try with this one. I just changed the podspec. Sorry for all the trouble.

**Comment by objectmethod** [comment]
No trouble at all!  You're the one contributing your time and efforts, and it is greatly appreciated!

I installed v1.0.2, and it still didn't work.  But then I noticed your earlier comment about changing the targeted platform version in my podfile from 7.0 to 6.0, and that worked.

Thanks again!!!
